name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - 'v[0-9]+.[0-9]+.[0-9]+-*'

jobs:
  # Builds the game for supported platforms
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v4
      - name: Export game
        uses: firebelley/godot-export@v6.0.0
        id: export
        with:
          godot_executable_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot-builds/releases/download/4.4.1-stable/Godot_v4.4.1-stable_export_templates.tpz
          relative_project_path: ./
          relative_export_path: build/
          archive_output: true
      - name: Upload builds
        uses: actions/upload-artifact@v4
        with:
          name: lacuna-builds
          path: build/*.zip

  # Creates a GitHub release of the game
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve builds
        uses: actions/download-artifact@v4
        with:
          name: lacuna-builds
          path: build/
      - name: Release game
        uses: softprops/action-gh-release@v2
        with:
          files: build/*.zip
